# Base configs
baseurl: "http://agathagorzelska.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Make-Up by Agatha Gorzelska"
subtitle: "My professional make-up website"
author: "Agatha Gorzelska"
bio: "I am a special lady"
publicise: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/agusiago"
  instagram: "https://www.instagram.com/agathagorzelska"
  linkedin: "https://www.linkedin.com/in/agatha-gorzelska-79b2a965/"
